/**
 * Generated by `pnpm --filter @cogworks/discord-kit emoji:sync`.
 * Do not edit by hand; run the sync script against the Discord application
 * and commit the result. Keyed by Discord application id.
 */
import type { EmojiManifest } from "./emoji.ts";

export const EMOJI_MANIFEST: EmojiManifest = {};
